# Generated by Django 5.2.9 on 2026-01-06 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IpRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_hash', models.CharField(max_length=64, unique=True)),
                ('ip_enc', models.TextField()),
                ('estado', models.CharField(choices=[('ok', 'ok'), ('cooldown', 'cooldown'), ('banned', 'banned')], default='ok', max_length=20)),
                ('cooldown_until', models.DateTimeField(blank=True, null=True)),
                ('login_stage', models.IntegerField(default=0)),
                ('login_fails', models.IntegerField(default=0)),
                ('forgot_round', models.IntegerField(default=0)),
                ('forgot_step', models.IntegerField(default=1)),
                ('forgot_fail1', models.IntegerField(default=0)),
                ('forgot_fail2', models.IntegerField(default=0)),
                ('geo_country', models.CharField(blank=True, max_length=40, null=True)),
                ('geo_region', models.CharField(blank=True, max_length=80, null=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('actor', models.CharField(blank=True, default='', max_length=80)),
                ('action', models.CharField(max_length=40)),
                ('entity', models.CharField(max_length=80)),
                ('entity_id', models.IntegerField(blank=True, null=True)),
                ('before_json', models.TextField(blank=True, null=True)),
                ('after_json', models.TextField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ts'], name='api_auditlo_ts_373b5a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(blank=True, default='', max_length=120)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ubicacion', models.CharField(blank=True, default='', max_length=200)),
                ('cantidad', models.IntegerField(default=0)),
                ('minimo', models.IntegerField(default=0)),
                ('propio', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['nombre'], name='api_materia_nombre_db9510_idx'), models.Index(fields=['tipo'], name='api_materia_tipo_ca9811_idx'), models.Index(fields=['precio'], name='api_materia_precio_2645d4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('apellido', models.CharField(max_length=120)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(blank=True, default='', max_length=30)),
                ('cedula_change_count', models.PositiveSmallIntegerField(default=0)),
                ('fecha_nacimiento_change_count', models.PositiveSmallIntegerField(default=0)),
                ('estado', models.CharField(choices=[('pendiente', 'pendiente'), ('activo', 'activo'), ('rechazado', 'rechazado'), ('baneado', 'baneado')], default='pendiente', max_length=20)),
                ('nivel', models.IntegerField(default=1)),
                ('sec_q1', models.CharField(max_length=200)),
                ('sec_a1_hash', models.CharField(max_length=200)),
                ('sec_q2', models.CharField(max_length=200)),
                ('sec_a2_hash', models.CharField(max_length=200)),
                ('signup_ip_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('signup_ip_enc', models.TextField(blank=True, null=True)),
                ('last_login_ip_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('last_login_ip_enc', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
