# Generated by Django 5.2.9 on 2026-01-10 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_usuario_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='en_uso',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='material',
            name='unidad',
            field=models.CharField(blank=True, default='unidad', max_length=40),
        ),
        migrations.AlterField(
            model_name='material',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='material',
            name='minimo',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='MaterialUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('responsable', models.CharField(blank=True, default='', max_length=120)),
                ('destino', models.CharField(blank=True, default='', max_length=200)),
                ('notas', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('abierto', 'abierto'), ('cerrado', 'cerrado'), ('cancelado', 'cancelado')], default='abierto', max_length=20)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usos_creados', to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('actor', models.CharField(blank=True, default='', max_length=80)),
                ('tipo', models.CharField(choices=[('salida', 'salida'), ('devolucion', 'devolucion'), ('consumo', 'consumo'), ('roto', 'roto'), ('perdido', 'perdido'), ('ajuste', 'ajuste')], max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('nota', models.CharField(blank=True, default='', max_length=240)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='api.material')),
                ('uso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='api.materialuso')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialUsoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_salida', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('cantidad_devuelta', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('cantidad_consumida', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('cantidad_rota', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('cantidad_perdida', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uso_items', to='api.material')),
                ('uso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.materialuso')),
            ],
        ),
        migrations.AddIndex(
            model_name='materialuso',
            index=models.Index(fields=['created_at'], name='api_materia_created_e8eb89_idx'),
        ),
        migrations.AddIndex(
            model_name='materialuso',
            index=models.Index(fields=['estado'], name='api_materia_estado_aa5096_idx'),
        ),
        migrations.AddIndex(
            model_name='materialmovimiento',
            index=models.Index(fields=['ts'], name='api_materia_ts_8d6bb6_idx'),
        ),
        migrations.AddIndex(
            model_name='materialmovimiento',
            index=models.Index(fields=['material'], name='api_materia_materia_461bf9_idx'),
        ),
        migrations.AddIndex(
            model_name='materialmovimiento',
            index=models.Index(fields=['tipo'], name='api_materia_tipo_22dfc5_idx'),
        ),
        migrations.AddIndex(
            model_name='materialusoitem',
            index=models.Index(fields=['uso'], name='api_materia_uso_id_0ecc03_idx'),
        ),
        migrations.AddIndex(
            model_name='materialusoitem',
            index=models.Index(fields=['material'], name='api_materia_materia_3625c1_idx'),
        ),
    ]
