# Generated by Django 5.2.9 on 2026-01-10 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_material_en_uso_material_unidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='material',
            name='vendible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='materialmovimiento',
            name='tipo',
            field=models.CharField(choices=[('salida', 'salida'), ('devolucion', 'devolucion'), ('consumo', 'consumo'), ('roto', 'roto'), ('perdido', 'perdido'), ('venta', 'venta'), ('ajuste', 'ajuste')], max_length=20),
        ),
        migrations.CreateModel(
            name='MaterialVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True, default='')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_creadas', to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialVentaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_venta_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='venta_items', to='api.material')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.materialventa')),
            ],
        ),
        migrations.AddIndex(
            model_name='materialventa',
            index=models.Index(fields=['created_at'], name='api_materia_created_04dfd7_idx'),
        ),
        migrations.AddIndex(
            model_name='materialventaitem',
            index=models.Index(fields=['venta'], name='api_materia_venta_i_e001fc_idx'),
        ),
        migrations.AddIndex(
            model_name='materialventaitem',
            index=models.Index(fields=['material'], name='api_materia_materia_17bef6_idx'),
        ),
    ]
